FROM python:3.12-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD ./README.md /app/
ADD ./pyproject.toml /app/
ADD ./.python-version /app/
ADD ./uv.lock /app/

ADD ./src /app/src

RUN uv sync --locked --no-dev

EXPOSE 8000

CMD ["uv", "run", "--no-sync", "fastapi", "run", "src/endpoint.py", "--port", "8000"]