/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vai2kYKW5JM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { CornerDownLeft } from "lucide-react";

interface ChatboxProps {
  handleSubmit: () => void;
  handleInputChange: (event: React.ChangeEvent<HTMLTextAreaElement>) => void;
  input: string;
}

export function Chatbox({
  handleSubmit,
  handleInputChange,
  input,
}: ChatboxProps) {
  const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      handleSubmit();
    }
  };

  return (
    <div className="flex-none p-2 bg-white border rounded-md w-full mb-3">
      <div className="flex-1">
        <Textarea
          className="w-full h-10 resize-none border-0 focus:outline-none focus-visible:outline-none focus-visible:ring-0 focus-visible:ring-offset-0"
          placeholder="Type a message... (@to mention)"
          value={input}
          onChange={handleInputChange}
          onKeyDown={handleKeyDown}
        />
      </div>
      <div className="flex items-center justify-between">
        <div className="text-xs text-gray-500 ml-4">@ Mention</div>
        <Button
          variant="secondary"
          className="py-0"
          size={"sm"}
          onMouseDown={handleSubmit}
        >
          <CornerDownLeft className="size-3 font-bold h-3 w-3" />
        </Button>
      </div>
    </div>
  );
}
