/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yT2hG9I7fmh
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import MarkdownRenderer from "./markdown-render";

import { type Message } from "ai";

interface ChatMessagesProps {
  messages: Message[];
}

import { useEffect, useRef } from "react";

export function ChatMessages({ messages }: ChatMessagesProps) {
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages]);

  return (
    <div
      key="1"
      className="grow flex flex-col items-start gap-4 p-4 md:p-8 w-full lg:mx-auto overflow-y-auto"
    >
      {messages.map((message, index) => (
        <div key={index} className="flex items-start gap-4 w-full">
          <div
            className={`${
              message.role === "user"
                ? "bg-gray-100 dark:bg-gray-950 dark:text-gray-50"
                : "bg-transparent"
            } rounded-lg p-3 max-w-[80%] flex-1`}
          >
            <div
              className={`font-medium text-sm ${
                message.role === "user"
                  ? ""
                  : "text-gray-500 dark:text-gray-400"
              }`}
            >
              {message.role === "user" ? "You" : "Assistant"}
            </div>
            <div className="prose prose-stone text-sm pl-0">
              <MarkdownRenderer content={message.content} />
            </div>
          </div>
        </div>
      ))}
      <div ref={messagesEndRef} />
    </div>
  );
}
