/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vai2kYKW5JM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { CornerDownLeft } from "lucide-react";

interface ChatboxProps {
  handleSubmit: (event: React.FormEvent<HTMLFormElement>) => void;
  handleInputChange: (event: React.ChangeEvent<HTMLTextAreaElement>) => void;
  input: string;
}

export function Chatbox({
  handleSubmit,
  handleInputChange,
  input,
}: ChatboxProps) {
  return (
    <form
      onSubmit={handleSubmit}
      className="p-2 bg-white border rounded-md w-full"
    >
      <div className="flex-1">
        <Textarea
          className="w-full h-10 resize-none border-0 focus:outline-none focus-visible:outline-none focus-visible:ring-0 focus-visible:ring-offset-0"
          placeholder="Type a message... (@to mention)"
          value={input}
          onChange={handleInputChange}
        />
      </div>
      <div className="flex items-center justify-between">
        <div className="text-xs text-gray-500 ml-4">@ Mention</div>
        <Button type="submit" variant="secondary" className="py-0" size={"sm"}>
          <CornerDownLeft className="size-3 font-bold h-3 w-3" />
        </Button>
      </div>
    </form>
  );
}
