ENVS = {
   "OTEL_EXPORTER_OTLP_PROTOCOL": "http",
   "OTEL_EXPORTER_OTLP_ENDPOINT": "https://otlp-gateway-prod-us-east-0.grafana.net/otlp",
   "OTEL_EXPORTER_OTLP_HEADERS": "Authorization=Basic%20OTM1MzU2OmdsY19leUp2SWpvaU1URXlOemN4TWlJc0ltNGlPaUp6ZEdGamF5MDVNelV6TlRZdGIzUnNjQzEzY21sMFpTMWxZWEowYUd0cGRDMXdiR0Y1SWl3aWF5STZJa2MxWnpWRlJuUTVaVE5oYzB3eVN6QXpPR0UzVURKdlJDSXNJbTBpT25zaWNpSTZJbkJ5YjJRdGRYTXRaV0Z6ZEMwd0luMTk="
}